load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "bazel_embedded",
    urls = [
         "https://github.com/alandovskis/bazel-embedded/archive/ci-stm32h7xx-examples.zip",
    ],
    build_file = "@//:bazel-embedded.BUILD",
)

load("@bazel_embedded//:bazel_embedded_deps.bzl", "bazel_embedded_deps")

bazel_embedded_deps()

load("@bazel_embedded//platforms:execution_platforms.bzl", "register_platforms")

register_platforms()

load(
    "@bazel_embedded//toolchains/compilers/gcc_arm_none_eabi:gcc_arm_none_repository.bzl",
    "gcc_arm_none_compiler",
)

gcc_arm_none_compiler()

load("@bazel_embedded//toolchains/gcc_arm_none_eabi:gcc_arm_none_toolchain.bzl", "register_gcc_arm_none_toolchain")

register_gcc_arm_none_toolchain()

load("//third_party_libs/devices/arm/st_microelectronics/stm32h7cube:stm32h7_repository.bzl", "stm32h7_repository")

stm32h7_repository(
    project_configs = {"minimal": "@bazel_embedded//devices/arm/st_microelectronics/stm32h7cube/minimal-cubemx-test:minimal_cubemx_project_config"},
)
